apiVersion: v1
kind: Pod
metadata:
  name: reports-pod
spec:
  containers:
  - name: alpine
    image: alpine:latest
    command: ['sleep', 'infinity']
    volumeMounts:
    - name: reports-pvc
      mountPath: /data
  restartPolicy: Never
  volumes:
  - name: reports-pvc
    persistentVolumeClaim:
      claimName: reports-pvc
