# Section : Permanent Volume claim for reports
apiVersion: v1
kind: PersistentVolume
metadata:
  name: reports-pv
spec:
  storageClassName: manual
  capacity:
    storage: 128Mi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/reports"