# Section : Permanent Volume claim for reports
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
  name: resources-pvc
spec:
  storageClassName: manual
  accessModes:
  - ReadWriteMany 
  resources:
    requests:
      storage: 32Mi